name = "NutrientLimitedGEMs"
uuid = "811c8c84-0892-4fbe-ad57-3c41131590a5"
authors = ["josePereiro <jose.pereiro.lab@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
ContextDBs = "f7273666-c521-4805-9666-bf343237b2c9"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ExtractMacro = "f86d3d12-fd5b-522c-99e9-61577282a1e9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ImgTools = "60a16571-0043-4368-b1b0-a5366d36b020"
MetX = "01815447-a018-4668-9805-89f51b3fc6a1"
MetXBase = "0b8c4419-604a-4c8e-9eed-0f79de4a140e"
MetXCultureHub = "c8a5ff98-18da-494d-98cc-f2d3bae7da4c"
MetXEP = "3facea42-c6d8-46ab-8896-2657a92d9f87"
MetXNetHub = "be9415a8-24b2-49ae-ba75-41eeaa9f722f"
MetXOptim = "672bf490-d3aa-44fe-a664-43445036b9de"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ProjFlows = "cac8b402-4888-4912-9502-a4f91500dd77"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
